os:
  - linux
services:
  - docker
sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "10.15.3"

branches:
  only:
    - /.*/

before_install:
  - sudo apt-get update

before_script:
  - npm install -g protractor
  - webdriver-manager update
#- webdriver-manager start

jobs:
  include:
    - stage: compile
      name: "Compile Stage"            # names the first Tests stage job
      script: npm --version
    - script: npm --version
      name: "Compile Stage2"
    - stage: test
      script: npm --version
    - stage: deploy
      script: npm --version


