os:
  - linux
services:
  - docker
sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "10.15.3"

branches:
  only:
    - /.*/

before_install:
  - sudo apt-get update

before_script:
  - npm install -g protractor
  - webdriver-manager update
# - webdriver-manager start

jobs:
  include:
    - compile
      script: npm --version
    - test
      script: npm --version
    - deploy
      script: npm --version


